### PR TITLE
Align akkahttp.server.JsonEntities signatures with the algebra

### LINKED ISSUE #210: Akka-Http JsonEntities signatures don't align with algebra
Looking at the implementation for [akkahttp.server.JsonEntities](https://github.com/julienrf/endpoints/blob/v0.8.0/akka-http/server/src/main/scala/endpoints/akkahttp/server/JsonEntities.scala#L21) the signatures of the (purportedly) implemented methods of the corresponding [algebra.JsonEntities](https://github.com/julienrf/endpoints/blob/master/algebras/algebra/src/main/scala/endpoints/algebra/JsonEntities.scala#L31) don't actually correspond correctly, as the documentation parameter is missing, e.g.

```scala
//from algebra.JsonEntities
def jsonRequest[A : JsonRequest](docs: Documentation = None): RequestEntity[A]
```

```scala
//from akkahttp.server.JsonEntities
def jsonRequest[A : JsonRequest]: RequestEntity[A] = Directives.entity[A](implicitly)
```

The net result is that it's not possible to easily implement an endpoint with akka-http mixin-in the  `server.JsonEntities` to the corresponding `server.Endpoint`, which results in missing implementations, and thus a compilation error

### PR DESCRIPTION
**Pull request by ivanopagano**
Fix #210

### CODE REVIEW

**Comment by ivanopagano** [comment]
@julienrf I hope this was what you had in mind?

**Comment by julienrf** [comment]
Awesome, can you squash the two commits?

**Comment by ivanopagano** [comment]
> Awesome, can you squash the two commits?

Do you want me to force push? Is there any cleaner way to do this, other than a new PR from totally different branch?

**Comment by julienrf** [comment]
Sure, just force push.

**Pull request merged**
