### PR TITLE
fixing some github doc links

### PR DESCRIPTION
**Pull request by bbarker**

### CODE REVIEW

**Comment by julienrf** [comment]
This is weird, the doc renders correctly on my machine (and on julienrf.github.io/endpoints). You have to run sbt from the root directory, not from the `documentation` directory. Not sure if that’s the issue…

**Comment by bbarker** [comment]
Sorry, i should have been more descriptive. The problem I have is that on  julienrf.github.io/endpoints, this link (for example) isn't working properly:

image

**Comment by julienrf** [comment]
Oh, indeed, thanks for reporting! We should fix this issue by adding `documentation/` to the path defined here: https://github.com/julienrf/endpoints/blob/master/documentation/manual/src/ornate.conf#L26

**Comment by bbarker** [comment]
Aha. As a matter of curiosity, I guess I'm still a bit confused about why the other urls I changed in this PR don't need the same change... but I've never used Ornate.

**Comment by bbarker** [comment]
Oh right, I see your comment about the relative directory bit.

**Pull request closed without merging**
